name: SentryBar
options:
  bundleIdPrefix: com.sentrybar
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.sentrybar.SentryBar
    MARKETING_VERSION: "0.6.0"
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: false
    INFOPLIST_FILE: SentryBar/Resources/Info.plist
    ENABLE_HARDENED_RUNTIME: true
    CODE_SIGN_STYLE: Automatic
    COMBINE_HIDPI_IMAGES: true

targets:
  SentryBar:
    type: application
    platform: macOS
    sources:
      - path: SentryBar
        excludes:
          - "**/*.plist"
    settings:
      base:
        PRODUCT_NAME: SentryBar
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    dependencies:
      - sdk: IOKit.framework
      - sdk: ServiceManagement.framework
      - sdk: UserNotifications.framework

  SentryBarTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SentryBarTests
    dependencies:
      - target: SentryBar
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SentryBar.app/Contents/MacOS/SentryBar"

schemes:
  SentryBar:
    build:
      targets:
        SentryBar: all
        SentryBarTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SentryBarTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
